import Ramon from "./Ramon.png";
import Photo from "./photo.png";
import Photo2 from "./photo2.png";
import Photo3 from "./photo3.png";
import Photo4 from "./photo4.png";
import Daniel from './Daniel.png';
import Patience from './Patience.jfif';
import Evlyne from './Evlyne.png';
import Petaaa from './Petaaa.png';
import Daniella from './photo.png';
import Sharone from './Sharone.png';
import Layla from './Layla.png';
import Moroe from './Moroe.png';
import Ashley from './Ramon.png';
import Online from '../assets/svgs/Online.svg';
import Offline from '../assets/svgs/Offline.svg';
import Wallet from '../assets/svgs/wallet.svg';
import Bitcoin from '../assets/svgs/bitcoin.svg';

export { Ramon, Photo, Photo2, Photo3, Photo4, Daniel, Patience, Evlyne, Petaaa, Daniella, Layla, Moroe, Ashley, Sharone, Online, Offline, Wallet, Bitcoin };
