import Ramon from "./Ramon.png";
import Photo from "./photo.png";
import Photo2 from "./photo2.png";
import Photo3 from "./photo3.png";
import Photo4 from "./photo4.png";
import Bitcoin from "./bitcoin.svg";
import Wallet2 from "./wallet (2).svg";
import Daniel from './Daniel.png';
import Patience from './Patience.jfif';
import Evlyne from './Evlyne.png';
import Petaaa from './Petaaa.png';
import Daniella from './photo.png';
import Sharone from './Sharone.png';
import Layla from './Layla.png';
import Moroe from './Moroe.png';
import Ashley from './Ramon.png';
import Online from './Online.svg';
import Offline from './Offline.svg';

export { Ramon, Photo, Photo2, Photo3, Photo4, Bitcoin, Wallet2, Daniel, Patience, Evlyne, Petaaa, Daniella, Layla, Moroe, Ashley, Sharone, Online, Offline };
